export const posts = [
    {
        id:1,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-1.jpg',
        name:'Trend news',
        title:'8 Romantic Gifts to Celebrate Your Wedding Anniversary',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 22, 2026',
    },
        {
        id:2,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-2.jpg',
        name:'Tips & Idea',
        title:'Red Rose - Flower of love of Greek Mythology',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 24, 2024',
    },
        {
        id:3,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-3.jpg',
        name:'DIY & Crafts',
        title:'Beautiful Mandalas Made From Flowers by Kathy Klein',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 15, 2021',
    },
        {
        id:4,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-4.jpg',
        name:'Trend News',
        title:'6 Unique Features of the Floret Online Workshop',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 29, 2022',
    },
        {
        id:5,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-5.jpg',
        name:'Tips & Idea',
        title:'Beyond Red Roses: Valentine’s Day Gift Guide',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 16, 2023',
    },
        {
        id:6,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-6.jpg',
        name:'DIY & Crafts',
        title:'A Year in Flowers Makes the New York Times Bestseller List',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 20, 2024',
    },
        {
        id:7,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-7.jpg',
        name:'Trend News',
        title:'Launching A Year in Flowersinto the World',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 06, 2020',
    },
        {
        id:8,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-8.jpg',
        name:'Tips & Idea',
        title:'Beyond Red Roses: Valentine’s Day Gift Guide',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 18, 2025',
    },
        {
        id:9,
        image:'https://preview.colorlib.com/theme/florist/img/blog/blog-9.jpg',
        name:'DIY & Crafts',
        title:'Pansies and Violas for Cut Flowers',
        text:'Flowers have a language all their own. In Victorian times, receiving a…',
        date:'MAY 22, 2026',
    },
]